### PR TITLE
Cargo rocket fuel

### PR DESCRIPTION
**Pull request by Reflex18**
This PR fixes the cargo rocket not accepting any fuel type. It does not fix it exploding on launch.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Does this fix the cargo rocket explode when landed as well? Issue was reported need to check it and link it here if so.

**Comment by Reflex18** [comment]
> Does this fix the cargo rocket explode when landed as well? Issue was reported need to check it and link it here if so.

No sadly it didnt which was why i didn't post it when i made the changes many months ago.
I might of messed something up since it appears to have some conflicts but i am not sure if that is an issue.

**Review by OneEyeMaker — APPROVED** [review]

**Comment by glowredman** [comment]
This wouldn't allow any higher tier fuel to be used - is this intended?

**Comment by Dream-Master** [comment]
@Reflex18

**Comment by Reflex18** [comment]
Oh no that isnt intended, it should take in any rocket fuel since it is classed as a tier two rocket.

**Comment by Dream-Master** [comment]
So can you make a fix ?

**Review by glowredman — APPROVED** [review]
Sorry, misread the code (which I wrote... 🤦‍♂️) - all good!

**Pull request merged**
