### PR TITLE
Removed recipes that are handled by GalaxySpace

### PR DESCRIPTION
**Pull request by glowredman**
The recipes and their NEI-representations of the T1-T3 Rockets, Cargo Rocket and Astro Miner will be handled by GalaxySpace. Previews can be found in [#galaxy-space-discussion](https://discordapp.com/channels/181078474394566657/739455313924587591/746075498131488939) on the GTNH Discord.

### CODE REVIEW

**Comment by glowredman** [comment]
I just realised, that the the commit `d5ae432` is not neccessary, but leads to a crash if GalaxySpace is not installed and one opens the NASA-Workbench (because it wants to open a GUI, but there is none)

**Comment by Dream-Master** [comment]
@glowredman can this be merged ?

**Comment by glowredman** [comment]
Yes, but if it's possible, leave the second commit out

**Comment by Dream-Master** [comment]
@glowredman Not possible just revert it and I'll merge it after.

**Pull request merged**
