### PR TITLE
Fix the ASM transformer from Galacticraft not working outside of dev env

### PR DESCRIPTION
**Pull request by Alexdoru**

### CODE REVIEW

**Comment by chochem** [comment]
supposedly this PR causes problems https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14728
(to be clear, I dont know what this PR does nor have I tested the problem myself.)

**Comment by Dream-Master** [comment]
If I remember right we have this issue long time ago . Then we add player api and it worked. Maybe this fix/code change does something @Alexdoru

**Comment by Glease** [comment]
the transformer fix is ok. it's the part that got enabled (which is not on the diff) that might have caused some problems. this will need more debugging before merging.

**Comment by Alexdoru** [comment]
The transformer should probably not destructively change the class to replace vanilla players with galacticraft players. It should probably be done another way by injecting into the vanilla player class.

**Comment by Alexdoru** [comment]
or tbf we could probably just delete that transformer since it was not working for years anyways nothing seemed to work wrong but now that we enable it again stuff is breaking

**Comment by Alexdoru** [comment]
This PR was an attempt at re-enabling an ASM transformer that wasn't running, but when enabling it, it broke the pack, so I guess we will leave it disabled, we could maybe delete it idk

**Pull request closed without merging**
