### PR TITLE
Update TickHandlerClient.java

### PR DESCRIPTION
**Pull request by jahtim**
After performance profiling ,this reflection here occupies 3% of all the cpu time of Client Thread, resulting ~3% fps drop. So this change makes fps increase by ~3%.

### CODE REVIEW

**Comment by Glease** [comment]
This again proves GC code is weird. why use random though?

**Comment by jahtim** [comment]
Because i'm not sure how this reflection works, I haven't found this class anywhere. To not break the code and minimize the impact, it reduce fps loss from 3% to 0.3% . It seems that 0.01 or 0.001 is also acceptable.

**Comment by TataTawa** [comment]
i found better

**Comment by TataTawa** [comment]
i found better

**Comment by jahtim** [comment]
i found better

**Pull request closed without merging**
