### PR TITLE
Experimental Oxygen Performance Improvement

### PR DESCRIPTION
**Pull request by glowredman**
OxygenUtil.testContactWithBreathableAir() does not test for sealed enviroments anymore, because that part of the method is recursive. As a result is the Oxygen Sealer not useable anymore, so I disabled its TileEntity.
Oxygen Bubbles will still work and be effective, because I think their logic is not performance-heavy, but having no possibility to create any oxygen enviroments on planets / moons / space stations would be a major gameplay downgrade.
If these changes are not enough, further changes are possible, though some profiling should be done beforehand.

### CODE REVIEW

**Review by Glease — COMMENTED** [review]
Code wise it's all right, not sure about the gameplay impact though. I personally use neither of these oxygen devices so I guess it's not that important.

**Comment by repo-alt** [comment]
Does it mean that planet stargates at official server spawns will lead to immediate death if your oxygen gear in wrong?

**Comment by glowredman** [comment]
No, damage is calculated as usual, so it will take some time until the player dies

**Comment by repo-alt** [comment]
So, not immediate, but death anyway. Ok, we'll just need to slap a warning _before_ the stargate, not after as it is now.

**Comment by Prometheus0000** [comment]
? They're going to another planet? And there's warnings in the QB? If there's so stupid to think they don't need to breathe on the moon, I say let them die.

**Comment by repo-alt** [comment]
Currently stargate leads to the sealed chamber with a breathable air, so that sentiment is not universally shared. I honestly don't have an opinion myself.

**Comment by boubou19** [comment]
if they die on the worldguard area, it needs a staff member to recover and clean the mess. But that happens rarely anyways.

**Comment by Prometheus0000** [comment]
Replace the O2 sealer with a O2 bubble?

**Review by bartimaeusnek — CHANGES_REQUESTED** [review]
I'm opposed of disabling this feature. Rather do something like checking the area once, then create a lookup table (some MultiMap) with Dimension <-> Block Mapping, and then re-excecute this check when stuff gets modified (EventHandlers).

**Comment by mitchej123** [comment]
> I'm opposed of disabling this feature. Rather do something like checking the area once, then create a lookup table (some MultiMap) with Dimension <-> Block Mapping, and then re-excecute this check when stuff gets modified (EventHandlers).

I'd be more in favor of this.  Caching the stuff and updating on events,

**Comment by glowredman** [comment]
@bartimaeusnek I think I kinda understand what you mean and I too think that'd be a better idea, but I have no idea how to implement that, partly because I never did something like that and partly because the GC code is very complex and covers many edge-cases. So maybe you can give it a shot I you have spare time :)
(I think It'd be better to start form scratch off of the MC1.7 branch)

**Pull request closed without merging**
