### PR TITLE
Handles SoulBound enchant

### PR DESCRIPTION
**Pull request by Ugachaga**
Also need to work https://github.com/GTNewHorizons/EnderIO/pull/4

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Ugachaga So far I understand the license, we not able to use a modified galacticraft version in the pack .

**Comment by Dream-Master** [comment]
This fork need to be update because not used own version for a long time

**Comment by Ugachaga** [comment]
Ehh.. yeah license. Well it is still doable without changing GC, but I'm not sure if it worth the effort. 
In that case no need to use GTNewHorizons/EnderIO#4.

**Comment by Dream-Master** [comment]
@Ugachaga revert allready. Is this just a cosmetic thing or a huge bug?

**Pull request closed without merging**
