### PR TITLE
cetena to tier 2

### PR DESCRIPTION
**Pull request by botn365**
bring cetena boosted to tier 2 to replace rp1 completly

### CODE REVIEW

**Comment by Prometheus0000** [comment]
If you're going to do that, why not just make it HOG for T2 instead? Cetane is kinda lame for 2 tiers. I'd rather it be a rocket-specific fuel though.

**Comment by botn365** [comment]
i dont know of any rocket fuels that is less complex then lmp but more complex then cetane and i dont think HOG should be a thing for rocket fuel
and rp1 is basicly realy pure light fuel so it would be less complex then cetane

**Comment by Prometheus0000** [comment]
At least it would be rocket fuel then. Or you could also just make something up.

**Comment by Prometheus0000** [comment]
Actually, what makes rocket fuel rocket fuel anyway? Could cetane be used on real rockets?

**Comment by botn365** [comment]
im prety sure it can

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
