### PR TITLE
Rework Rocket Fuel API

### PR DESCRIPTION
**Pull request by glowredman**
The old API didn't allow a lower tier rocket having fewer fuels than a higher tier rocket. I want the Shuttle Rocket to only accept T8 fuels but due to how the Shuttle Rocket works, it is defined as T0\*, so it would accept all possible fuels before. The new API allows the fuels to be specified per class. Due to the old API only ever being used in GC, this change doesn't affect any other mods.

This PR also adresses @eigenraven's review of #76 and marks NEI as hard-dep (it has been like this since the tiered rocket fuels have been introduced, it just wasn't specified in the `@Mod`-annotation).

\* so that the player can't use it to access any planet/moon, just the Mothership

### CODE REVIEW

**Comment by chochem** [comment]
> Due to the old API only ever being used in GC

arent the current fuels added in gt++?

**Comment by glowredman** [comment]
> > Due to the old API only ever being used in GC
> 
> arent the current fuels added in gt++?

The *fluids* yes, but the code used to define which fluids can be used to fuel rockets was completely in GC (look at the diff of [`RecipeManagerGC`](https://github.com/GTNewHorizons/Galacticraft/pull/77/files#diff-e1e909acf186df484ef28e1e788685e50e2dc2e3ac0c24d9ee93e1e6aa2cce7e))

**Review by minecraft7771 — COMMENTED** [review]
Code looks good so far. From what I understand this changes rocket fuel so you can't fuel a low tier rocket with a high tier fuel anymore? Is that correct and intended?

**Comment by glowredman** [comment]
You still can, see lines 73 to 78 in [RecipeManagerGC](https://github.com/GTNewHorizons/Galacticraft/blob/rework-fuel-recipes/src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java#L73-L78).

**Review by minecraft7771 — APPROVED** [review]

**Comment by minecraft7771** [comment]
Ah I missed that it's a map object that allows duplicates.

**Pull request merged**
